#!/bin/bash
#
# This software is a part of ISAR.
# Copyright (C) 2015-2017 ilbers GmbH
#
# TODO
# - bash required due to $LINENO, not supported by dash 0.5.7-4+b1.

TMPDIR=tmp
TESTDIR=$TMPDIR/test
CONSOLE_OUTPUT=$TESTDIR/isar_console
PID_FILE=$TESTDIR/qemu_pid

VM_TIMEOUT=120
MATCH_STR="isar login: "

DEBUG=0

. isar_test.sh
. isar_debug.sh
. isar_qemu.sh


# We expect to be called in Isar build directory, check for that
# TODO: A better way to determine whether we are in the build directory?
if [ ! -d "$TMPDIR" ]; then
    echo "$0: ERROR: `readlink -f $TMPDIR` doesn't exist" >&2
    echo "$0 should be executed from Isar build directory" >&2
    exit $RC_UNRESOLVED
fi
mkdir -p "$TESTDIR"

es=$RC_PASS

# ARM machine
run_test arm wheezy
run_test arm jessie
run_test arm stretch

# AMD64 machine
run_test amd64 jessie
run_test amd64 stretch

# i386 machine
run_test i386 jessie
run_test i386 stretch

exit $es
