#!/bin/sh
#
# This software is a part of ISAR.
# Copyright (C) 2015-2017 ilbers GmbH

TMPDIR=tmp
TESTDIR=$TMPDIR/test
CONSOLE_OUTPUT=$TESTDIR/isar_console
PID_FILE=$TESTDIR/qemu_pid

check_output() {
    str=$(tail -1 $CONSOLE_OUTPUT)

    if [ "$str" = "isar login: " ]; then
        echo "Test: PASSED"
    else
        echo "Test: FAIL"
    fi
}

run_test () {
    ARCH=$1
    DISTRO=$2

    echo "-------------------------------------------------"
    echo "Testing Isar [$DISTRO] image for [$ARCH] machine:"

    # Start QEMU with Isar image
    start_vm -a $ARCH -d $DISTRO -o $CONSOLE_OUTPUT -p $PID_FILE > /dev/null 2>&1 &
    sleep 30
    kill `cat $PID_FILE`

    # Check output
    check_output

    # Keep test artifacts for debugging:
    # - $CONSOLE_OUTPUT
    # - $PID_FILE
}


# We expect to be called in Isar build directory, check for that
# TODO: A better way to determine whether we are in the build directory?
if [ ! -d "$TMPDIR" ]; then
    echo "$0: ERROR: `readlink -f $TMPDIR` doesn't exist" >&2
    echo "$0 should be executed from Isar build directory" >&2
    exit $RC_UNRESOLVED
fi
mkdir -p "$TESTDIR"

# ARM machine
run_test arm wheezy
run_test arm jessie
run_test arm stretch

# AMD64 machine
run_test amd64 jessie
run_test amd64 stretch

# i386 machine
run_test i386 jessie
run_test i386 stretch
